name: CI

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [development]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.2.0
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: npm ci
      #- name: Run Tests
        #run: npm run test

  build:
    name: Docker Hub
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build and publish Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: puneetgopinath/discord_welcome-bot
          tag_with_ref: true
